; Confs PHP spécifiques à la production

; OPcache : ne pas valider les timestamps (perf max — exige un restart pour
; appliquer les changements de code, ce qui correspond à un déploiement)
opcache.validate_timestamps = 0
opcache.preload = /app/config/preload.php
opcache.preload_user = root

; Réalpath cache plus agressif en prod
realpath_cache_size = 4096K
realpath_cache_ttl = 600

; Pas d'affichage d'erreurs en prod
display_errors = Off
display_startup_errors = Off
