; Confs PHP spécifiques au développement local

; OPcache : valider les timestamps pour recharger les fichiers modifiés sans
; restart du conteneur. Légèrement plus lent mais indispensable en dev.
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

; Erreurs : on les affiche en dev pour debug rapide
display_errors = On
display_startup_errors = On

; Xdebug désactivé par défaut, activé via XDEBUG_MODE=debug dans .env.local
xdebug.mode = ${XDEBUG_MODE}
xdebug.client_host = ${XDEBUG_CLIENT_HOST}
xdebug.client_port = 9003
xdebug.start_with_request = trigger
xdebug.idekey = PHPSTORM
